package vista;


import controlador.ControladorPaneles;
import controlador.DatosTarjeta;
import controlador.Sentencias;
import controlador.Usuario;
import javax.swing.JPanel;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class Carrito extends javax.swing.JFrame implements ControladorPaneles{
    private int panelActual = 0; // 0 = Carrito; 1 = Identificacion; 2 = Envio; 3 = Pago; 4 = Boleta;
    Connection c;
    Precios precios = new Precios();
    Envio envio;
    Usuario usuario;
    Identificacion identificacion = new Identificacion(c);
    Pago pago = new Pago(c, usuario);
    DatosTarjeta tarjeta = new DatosTarjeta();
    ArrayList<Long> numTarjeta = new ArrayList<>();
    ArrayList<String> fechaVencimiento = new ArrayList<>();
    ArrayList<Integer> cvv = new ArrayList<>();
    boolean sonIguales = false;
    
    public Carrito(Connection c) {
        initComponents();
        this.refrescarPanel(precios.getPanel(), panel_precios);
        this.c = c;
        envio = new Envio(c, precios, usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formulario = new javax.swing.JPanel();
        img2 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        codigodescuento = new javax.swing.JLabel();
        personadescuento = new javax.swing.JTextField();
        panel_precios = new javax.swing.JPanel();
        btn_multifuncional = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        formulario.setBackground(new java.awt.Color(255, 255, 255));
        formulario.setPreferredSize(new java.awt.Dimension(500, 480));

        img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pantaloncolor.jpeg.png"))); // NOI18N
        img2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        img1.setBackground(new java.awt.Color(102, 102, 102));
        img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pantalonN.jpeg.png"))); // NOI18N
        img1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Pantalon talla M  $9.990");

        jLabel7.setText("Pantalon talla M  $9.990");

        codigodescuento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        codigodescuento.setText("Código de descuento:");

        personadescuento.setBackground(new java.awt.Color(222, 222, 222));
        personadescuento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        personadescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personadescuentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formularioLayout = new javax.swing.GroupLayout(formulario);
        formulario.setLayout(formularioLayout);
        formularioLayout.setHorizontalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioLayout.createSequentialGroup()
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formularioLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(img1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(img2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formularioLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(codigodescuento)
                        .addGap(27, 27, 27)
                        .addComponent(personadescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        formularioLayout.setVerticalGroup(
            formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigodescuento)
                    .addComponent(personadescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formularioLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(148, 148, 148))
        );

        javax.swing.GroupLayout panel_preciosLayout = new javax.swing.GroupLayout(panel_precios);
        panel_precios.setLayout(panel_preciosLayout);
        panel_preciosLayout.setHorizontalGroup(
            panel_preciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        panel_preciosLayout.setVerticalGroup(
            panel_preciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        btn_multifuncional.setText("Ir a identificación");
        btn_multifuncional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multifuncionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(formulario, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(panel_precios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_multifuncional)
                        .addGap(105, 105, 105))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(panel_precios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_multifuncional)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(formulario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personadescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personadescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personadescuentoActionPerformed

    private void btn_multifuncionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multifuncionalActionPerformed
        
        switch (panelActual){
            case 0 -> {
                this.refrescarPanel(identificacion.getPanel(), formulario);
                this.actualizarBoton(1, "Continuar a envio");
                
            }
            case 1 -> {
                usuario = this.enviarDatosUsuarios(identificacion.getNombretxt().getText(), identificacion.getApellidotxt().getText(), identificacion.getRuttxt().getText(), identificacion.getCorreotxt().getText(), Long.parseLong(identificacion.getNumTeleftxt().getText()));
                this.refrescarPanel(envio.getPanel(), formulario);
                this.actualizarBoton(2, "Continuar al pago");
            }
            case 2 -> {
                
                this.enviarDatosEnvio(usuario);
                this.refrescarPanel(pago.getPanel(), formulario);
                this.actualizarBoton(3, "Pagar");
            }
            case 3 -> {
                this.guardarDatosTarjeta(Long.parseLong(pago.getNumTarjetaTXT().getText()), pago.getFechaVencimientoTXT().getText(), Integer.parseInt(pago.getCvvTXT().getText()));
                this.compararDatosTarjeta();
                if (sonIguales){
                    this.refrescarPanel(new Boleta(c, precios, usuario, tarjeta).getPanel(), jPanel1);
                    new Sentencias().insertarDatosUsuario(c, usuario.getNombre(), usuario.getApellido(), usuario.getRut(), usuario.getCorreo(), usuario.getDireccion(), (int) usuario.getNumeroTelefono());
                    this.actualizarBoton(4, "Continuar a envio");
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_multifuncionalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_multifuncional;
    private javax.swing.JLabel codigodescuento;
    private javax.swing.JPanel formulario;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_precios;
    private javax.swing.JTextField personadescuento;
    // End of variables declaration//GEN-END:variables

    @Override
    public javax.swing.JPanel getPanel(){
        return jPanel1;
    }
    
    @Override
    public void refrescarPanel(JPanel panel, JPanel bg){
        bg.removeAll();
        bg.add(panel);
        bg.revalidate();
        bg.repaint();
        
    }
    
    private void actualizarBoton(int indice, String mensaje){
        panelActual = indice;
        btn_multifuncional.setText(mensaje);
    }
    
    private Usuario enviarDatosUsuarios(String nombre, String apellido, String rut, String correo, long numeroTelefono){
        Usuario user1 = new Usuario();
        user1.setNombre(nombre);
        user1.setApellido(apellido);
        user1.setCorreo(correo);
        user1.setRut(rut);
        user1.setNumeroTelefono(numeroTelefono);
        return user1;
    }
    
    private Usuario enviarDatosEnvio(Usuario usuario){
        String direccion = envio.getCalleTXT().getText() + " " + envio.getNumCasaTXT().getText() + " "+ envio.getOpcionalTXT().getText();
        usuario.setDireccion(direccion);
        return usuario;
    }
    
    private void guardarDatosTarjeta(long numeroTarjeta, String fechaVencimiento, int cvv){
        tarjeta.setNumeroTarjeta(numeroTarjeta);
        tarjeta.setFechaVencimiento(fechaVencimiento);
        tarjeta.setCvv(cvv);
    }
    
    public void compararDatosTarjeta(){
        Sentencias s = new Sentencias();
        numTarjeta = s.recuperarNumTarjeta(c);
        fechaVencimiento = s.recuperarFechaVen(c);
        cvv = s.recuperarCvv(c);
        sonIguales = this.comparacion();
        
    }
    
    private boolean comparacion(){
        boolean flag1 = false, flag2 = false, flag3 = false;
        for (Long numero : numTarjeta){
            if (numero.equals(Long.valueOf(tarjeta.getNumeroTarjeta()))) flag1 = true;
        }
        
        for (String fechaVen : fechaVencimiento){
            if (fechaVen.equals(tarjeta.getFechaVencimiento())) flag2 = true;
        }
        
        for (int Cvv : cvv){
            if (Cvv == tarjeta.getCvv()) flag3 = true;
        }
        
        return flag1 == flag2 == flag3;
    }
}
