package vista;

import controlador.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JPanel;


/**
 *
 * @author familia
 */
public class Envio extends javax.swing.JFrame implements ControladorPaneles{
    Connection c;
    ArrayList<String> nombreComunas = new ArrayList<>();
    ArrayList<Integer> precioEnvio = new ArrayList<>();
    String selected = "";
    int indice;
    Precios precios;
    
    public Envio(Precios precios) {
        initComponents();
        desplegableComuna.removeAllItems();
        this.listarComunas(c);
        this.precios = precios;
        
    }
    
    public Envio(Connection c, Precios precios){
        initComponents();
        desplegableComuna.removeAllItems();
        this.listarComunas(c);
        this.c = c;
        this.precios = precios;
    }

    public ArrayList<String> getNombreComunas() {
        return nombreComunas;
    }

    public void setNombreComunas(ArrayList<String> nombreComunas) {
        this.nombreComunas = nombreComunas;
    }

    public ArrayList<Integer> getPrecioEnvio() {
        return precioEnvio;
    }

    public void setPrecioEnvio(ArrayList<Integer> precioEnvio) {
        this.precioEnvio = precioEnvio;
    }

    public JComboBox<String> getDesplegableComuna() {
        return desplegableComuna;
    }

    public String getStringDesplegableComuna() {
        return selected;
    }

    public void setSelectedDesplegableComuna(String selected) {
        this.selected = selected;
    }

    public int getIndice() {
        return indice;
    }

    public void setIndice(int indice) {
        this.indice = indice;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comuna = new javax.swing.JLabel();
        envioo = new javax.swing.JLabel();
        textname1 = new javax.swing.JTextField();
        textname2 = new javax.swing.JTextField();
        textname3 = new javax.swing.JTextField();
        textname4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        desplegableComuna = new javax.swing.JComboBox<>();
        btn_actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        comuna.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comuna.setText("Comuna");

        envioo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        envioo.setText("Envío");

        textname1.setBackground(new java.awt.Color(204, 204, 204));
        textname1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textname1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textname1ActionPerformed(evt);
            }
        });

        textname2.setBackground(new java.awt.Color(204, 204, 204));
        textname2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textname2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textname2ActionPerformed(evt);
            }
        });

        textname3.setBackground(new java.awt.Color(204, 204, 204));
        textname3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textname3.setText("opcional");
        textname3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textname3ActionPerformed(evt);
            }
        });

        textname4.setBackground(new java.awt.Color(204, 204, 204));
        textname4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textname4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textname4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Calle");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Número de casa");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Información adicional");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Destinatario");

        desplegableComuna.setBackground(new java.awt.Color(204, 204, 204));
        desplegableComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegableComuna.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        desplegableComuna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desplegableComunaMouseClicked(evt);
            }
        });
        desplegableComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegableComunaActionPerformed(evt);
            }
        });

        btn_actualizar.setText("Actualizar selección");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(desplegableComuna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comuna)
                                .addComponent(textname1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(textname3, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(textname4, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(textname2))
                            .addComponent(btn_actualizar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(envioo)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(envioo)
                .addGap(24, 24, 24)
                .addComponent(comuna, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desplegableComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualizar))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textname1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textname4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textname2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textname3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textname1ActionPerformed

    private void textname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textname2ActionPerformed

    private void textname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textname3ActionPerformed

    private void textname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textname4ActionPerformed

    private void desplegableComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegableComunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegableComunaActionPerformed

    private void desplegableComunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desplegableComunaMouseClicked
        
    }//GEN-LAST:event_desplegableComunaMouseClicked

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        this.setDatosComunas();
        System.out.println("Comuna seleccionada: " + this.getStringDesplegableComuna());
        System.out.println("Indice: " + this.getIndice());
        this.actualizarPrecio();
        
    }//GEN-LAST:event_btn_actualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JLabel comuna;
    private javax.swing.JComboBox<String> desplegableComuna;
    private javax.swing.JLabel envioo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textname1;
    private javax.swing.JTextField textname2;
    private javax.swing.JTextField textname3;
    private javax.swing.JTextField textname4;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getPanel() {
        return jPanel1;
    }

    @Override
    public void refrescarPanel(JPanel panel, JPanel bg) {
    }
    
    private void listarComunas(Connection c){
        try {
            nombreComunas = new Sentencias().recuperarNombreComunas(c);
            precioEnvio = new Sentencias().recuperarPrecioEnvio(c);
            
            for (String comuna: nombreComunas) {
            desplegableComuna.addItem(comuna);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void setDatosComunas(){
        String palabra = desplegableComuna.getSelectedItem().toString();
        int index = desplegableComuna.getSelectedIndex();
        setSelectedDesplegableComuna(palabra);
        setIndice(index);
    }
    
    private void actualizarPrecio(){
        int precio = this.getPrecioEnvio().get(this.getIndice());
        precios.setEnvio_TXT(String.valueOf(precio));
    }
        
}
